a="Vishval"
print("Type of",a,"=",type(a))
b=10
print("Type of",b,"=",type(b))
c=6.8
print("Type of",c,"=",type(c))
d=1j
print("Type of",d,"=",type(d))
e=["Hii","Hello"]
print("Type of",e,"=",type(e))
f=(10,30,20)
print("Type of",f,"=",type(f))
g={1,2,3,4,5}
print("Type of",g,"=",type(g))
h={1:"Hii",2:"Hello"}
print("Type of",h,"=",type(h))
i=frozenset(('Hi','Hello'))
print("Type of",i,"=",type(i))
j=bytes(5)
print("Type of",j,"=",type(j))
k=bool(5)
print("Type of",k,"=",type(k))
l=bytearray(5)
print("Type of",l,"=",type(l))
m=range(4)
print("Type of",m,"=",type(m))
n=memoryview(bytearray(5))
print("Type of",n,"=",type(n))
